// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4B-y0lt4J4fJixBqlwml9x0rZkfnDpYg',
    appId: '1:1046036539952:android:84e89899e560e87f575bf5',
    messagingSenderId: '1046036539952',
    projectId: 'notes-209a5',
    storageBucket: 'notes-209a5.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoiPQwmFBq1IpRJUc4gY5y7LYwy3HtQaY',
    appId: '1:1046036539952:web:2b891bf74a9d0aae575bf5',
    messagingSenderId: '1046036539952',
    projectId: 'notes-209a5',
    authDomain: 'notes-209a5.firebaseapp.com',
    storageBucket: 'notes-209a5.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN_U1G57kF8xlhZsRbK1xpGEWyMYPInyY',
    appId: '1:1046036539952:ios:9f92ea41c743d2bf575bf5',
    messagingSenderId: '1046036539952',
    projectId: 'notes-209a5',
    storageBucket: 'notes-209a5.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN_U1G57kF8xlhZsRbK1xpGEWyMYPInyY',
    appId: '1:1046036539952:ios:9f92ea41c743d2bf575bf5',
    messagingSenderId: '1046036539952',
    projectId: 'notes-209a5',
    storageBucket: 'notes-209a5.appspot.com',
    iosBundleId: 'com.example.demo',
  );

}